trigger:
- master

pool:
  name: my-vms

variables:
  imageName: frontend-app

stages:
- stage: Build
  displayName: 'Build and Push to Nexus'
  jobs:
  - job: DockerBuild
    displayName: 'Build and Push Docker Image'
    steps:

    - checkout: self

    - script: |
        shortCommit=$(echo $(Build.SourceVersion) | cut -c1-7)
        tag="dev-${shortCommit}-$(date +%Y-%m-%d)-$(Build.BuildId)"
        echo "##vso[task.setvariable variable=customTag]$tag"
      displayName: 'Generate Docker Tag'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: NexusDockerRegistry
        repository: $(imageName)
        command: build
        Dockerfile: Frontend/Dockerfile
        tags: |
          $(customTag)

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        containerRegistry: NexusDockerRegistry
        repository: $(imageName)
        command: push
        tags: |
          $(customTag)
