trigger:
- master

pool:
  name: my-vms

variables:
  imageName: frontend-app
  shortCommit: $[format('{0}', variables['Build.SourceVersion'].Substring(0, 7))]
  year: $[format('{0:yyyy}', pipeline.startTime)]
  month: $[format('{0:MM}', pipeline.startTime)]
  day: $[format('{0:dd}', pipeline.startTime)]
  tag: dev-$(shortCommit)-$(year)-$(month)-$(day)-$(Build.BuildId)

stages:
- stage: Build
  displayName: 'Build and Push to Nexus'
  jobs:
  - job: DockerBuild
    steps:
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        containerRegistry: NexusDockerRegistry
        repository: $(imageName)
        command: build
        Dockerfile: Frontend/Dockerfile
        tags: |
          $(tag)

    - task: Docker@2
      displayName: 'Push Docker image to Nexus'
      inputs:
        containerRegistry: NexusDockerRegistry
        repository: $(imageName)
        command: push
        tags: |
          $(tag)
