trigger:
- master

pool:
  name: my-vms

variables:
  imageName: frontend-app
  tag: $(Build.BuildId)

stages:
- stage: Build
  displayName: 'Build and Push to Nexus'
  jobs:
  - job: DockerBuild
    steps:
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        containerRegistry: NexusDockerRegistry
        repository: $(imageName)
        command: build
        Dockerfile: Frontend/Dockerfile
        tags: |
          $(tag)

    - task: Docker@2
      displayName: 'Push Docker image to Nexus'
      inputs:
        containerRegistry: NexusDockerRegistry
        repository: $(imageName)
        command: push
        tags: |
          $(tag)
