trigger:
- master

pool:
  name: my-vms

variables:
  imageName: frontend-app

stages:
- stage: Build
  displayName: 'Build and Push to Nexus'
  jobs:
  - job: DockerBuild
    displayName: 'Build and Push Image'
    steps:

    - checkout: self

    - script: |
        echo "##[group]Generating Docker tag..."
        shortCommit=$(echo $(Build.SourceVersion) | cut -c1-7)
        tag="dev-${shortCommit}-$(date +%Y-%m-%d)-$(Build.BuildId)"
        echo "Generated tag: $tag"
        echo "##vso[task.setvariable variable=customTag]$tag"
        echo "##[endgroup]"
      displayName: 'Generate Custom Tag'
      shell: bash   # ✅ Correct location

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        containerRegistry: NexusDockerRegistry
        repository: $(imageName)
        command: build
        Dockerfile: Frontend/Dockerfile
        tags: |
          $(customTag)

    - task: Docker@2
      displayName: 'Push Docker image to Nexus'
      inputs:
        containerRegistry: NexusDockerRegistry
        repository: $(imageName)
        command: push
        tags: |
          $(customTag)
